import { describe, it } from 'node:test';
import assert from 'node:assert';
import { generateWorkflows } from '../generators/workflow.js';
import type { CronConfig } from '../utils/loader.js';

describe('generateWorkflows', () => {
  it('generates workflow for agent schedule with pr strategy', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'nightly-review',
        cron: '0 2 * * *',
        agent: 'code-reviewer',
        adapter: 'claude',
        prompt: 'Review PRs',
        branch: {
          strategy: 'pr',
          base: 'main',
          pr_labels: ['automated'],
        },
      }],
      settings: {
        workflow_prefix: 'gitcron-',
      },
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    assert.strictEqual(workflows[0].filename, 'gitcron-nightly-review.yml');
    assert.ok(workflows[0].content.includes('AUTO-GENERATED by gitcron'));
    assert.ok(workflows[0].content.includes('cron:'));
    assert.ok(workflows[0].content.includes('gh pr create'));
    assert.ok(workflows[0].content.includes('gitagent run'));
  });

  it('generates workflow for command schedule with none strategy', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'lint-check',
        cron: '0 6 * * 1',
        command: 'npm run lint',
        branch: { strategy: 'none' },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    assert.ok(workflows[0].content.includes('npm run lint'));
    assert.ok(!workflows[0].content.includes('gitagent'));
    assert.ok(!workflows[0].content.includes('git commit'));
  });

  it('generates workflow for commit strategy', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'auto-fix',
        cron: '0 3 * * *',
        command: 'npm run fix',
        branch: { strategy: 'commit', base: 'main' },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    assert.ok(workflows[0].content.includes('git push origin main'));
    assert.ok(!workflows[0].content.includes('gh pr create'));
  });

  it('skips disabled schedules', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'disabled-task',
        cron: '0 0 * * *',
        command: 'echo hi',
        enabled: false,
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 0);
  });

  it('generates workflow for recurring reminder', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      reminders: [{
        name: 'weekly-status',
        type: 'recurring',
        cron: '0 9 * * 1',
        action: {
          type: 'issue',
          title: 'Weekly Status',
          labels: ['reminder'],
        },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    assert.strictEqual(workflows[0].filename, 'gitcron-reminder-weekly-status.yml');
    assert.ok(workflows[0].content.includes('gh issue create'));
    assert.ok(workflows[0].content.includes('Weekly Status'));
  });

  it('generates workflow for one-shot reminder with guard', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      reminders: [{
        name: 'onboarding-check',
        type: 'one-shot',
        at: '2026-03-12T09:00:00Z',
        action: {
          type: 'issue',
          title: 'How is setup going?',
        },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    assert.ok(workflows[0].content.includes('Check if one-shot should fire'));
  });

  it('generates workflow using gitclaw adapter', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'gitclaw-review',
        cron: '0 2 * * *',
        agent: 'reviewer',
        adapter: 'gitclaw',
        prompt: 'Review code',
        agent_source: {
          type: 'local',
          path: './agents/reviewer',
        },
        branch: {
          strategy: 'pr',
          base: 'main',
          pr_labels: ['automated'],
        },
        secrets: ['ANTHROPIC_API_KEY'],
      }],
    };

    const workflows = generateWorkflows(config);
    assert.strictEqual(workflows.length, 1);
    // Should use gitclaw, not gitagent
    assert.ok(workflows[0].content.includes('Install gitclaw'));
    assert.ok(workflows[0].content.includes('npm install -g gitclaw'));
    assert.ok(workflows[0].content.includes('Run agent (gitclaw)'));
    assert.ok(workflows[0].content.includes('gitclaw -d'));
    assert.ok(!workflows[0].content.includes('gitagent run'));
    // Should still have PR creation and secrets
    assert.ok(workflows[0].content.includes('gh pr create'));
    assert.ok(workflows[0].content.includes('ANTHROPIC_API_KEY'));
  });

  it('generates workflow using gitagent for non-gitclaw adapters', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'openai-task',
        cron: '0 3 * * *',
        agent: 'analyzer',
        adapter: 'openai',
        prompt: 'Analyze code',
        branch: { strategy: 'none' },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.ok(workflows[0].content.includes('Install gitagent'));
    assert.ok(workflows[0].content.includes('gitagent run'));
    assert.ok(workflows[0].content.includes('--adapter openai'));
    assert.ok(!workflows[0].content.includes('gitclaw'));
  });

  it('includes failure notification steps', () => {
    const config: CronConfig = {
      spec_version: '0.1.0',
      name: 'test-project',
      schedules: [{
        name: 'notified-task',
        cron: '0 2 * * *',
        command: 'echo test',
        notify: {
          on_failure: [{
            type: 'issue',
            title: 'Task failed',
            labels: ['bug'],
          }],
        },
      }],
    };

    const workflows = generateWorkflows(config);
    assert.ok(workflows[0].content.includes('Notify on failure'));
    assert.ok(workflows[0].content.includes('failure()'));
  });
});
