import type { Schedule, Reminder } from '../utils/loader.js';

interface WorkflowStep {
  name: string;
  uses?: string;
  with?: Record<string, string | number | boolean>;
  run?: string;
  if?: string;
  env?: Record<string, string>;
}

export function checkoutStep(): WorkflowStep {
  return {
    name: 'Checkout',
    uses: 'actions/checkout@v4',
    with: { 'fetch-depth': 0 },
  };
}

export function setupNodeStep(): WorkflowStep {
  return {
    name: 'Setup Node.js',
    uses: 'actions/setup-node@v4',
    with: { 'node-version': '20' },
  };
}

export function installGitagentStep(): WorkflowStep {
  return {
    name: 'Install gitagent',
    run: 'npm install -g @shreyaskapale/gitagent',
  };
}

export function installGitclawStep(): WorkflowStep {
  return {
    name: 'Install gitclaw',
    run: 'npm install -g gitclaw',
  };
}

export function createBranchStep(schedule: Schedule): WorkflowStep {
  const nameTemplate = schedule.branch?.name_template || `gitcron/${schedule.name}/$(date +%Y-%m-%d)`;
  const branchExpr = nameTemplate
    .replace('{{name}}', schedule.name)
    .replace('{{date}}', '$(date +%Y-%m-%d)');

  return {
    name: 'Create branch',
    run: [
      `BRANCH="${branchExpr}"`,
      'git checkout -b "$BRANCH"',
      'echo "GITCRON_BRANCH=$BRANCH" >> "$GITHUB_ENV"',
    ].join('\n'),
  };
}

export function runAgentStep(schedule: Schedule): WorkflowStep {
  const prompt = schedule.prompt || '';
  const adapter = schedule.adapter || 'claude';
  const agentDir = schedule.agent_source?.path || '.';

  const env: Record<string, string> = {};
  if (schedule.secrets) {
    for (const secret of schedule.secrets) {
      env[secret] = `\${{ secrets.${secret} }}`;
    }
  }

  return {
    name: 'Run agent',
    env: Object.keys(env).length > 0 ? env : undefined,
    run: [
      `PROMPT="\${{ inputs.prompt || '${prompt.replace(/'/g, "\\'")}' }}"`,
      `gitagent run --dir "${agentDir}" --adapter ${adapter} --prompt "$PROMPT"`,
    ].join('\n'),
  };
}

export function runGitclawAgentStep(schedule: Schedule): WorkflowStep {
  const prompt = schedule.prompt || '';
  const agentDir = schedule.agent_source?.path || '.';

  const env: Record<string, string> = {};
  if (schedule.secrets) {
    for (const secret of schedule.secrets) {
      env[secret] = `\${{ secrets.${secret} }}`;
    }
  }

  const modelFlag = schedule.env?.GITCLAW_MODEL ? ` -m "${schedule.env.GITCLAW_MODEL}"` : '';

  return {
    name: 'Run agent (gitclaw)',
    env: Object.keys(env).length > 0 ? env : undefined,
    run: [
      `PROMPT="\${{ inputs.prompt || '${prompt.replace(/'/g, "\\'")}' }}"`,
      `gitclaw -d "${agentDir}"${modelFlag} -p "$PROMPT"`,
    ].join('\n'),
  };
}

export function runCommandStep(schedule: Schedule): WorkflowStep {
  return {
    name: 'Run command',
    run: schedule.command!,
  };
}

export function commitStep(schedule: Schedule, authorName: string, authorEmail: string): WorkflowStep {
  return {
    name: 'Commit changes',
    run: [
      `git config user.name "${authorName}"`,
      `git config user.email "${authorEmail}"`,
      'git add -A',
      `git diff --cached --quiet || git commit -m "gitcron: ${schedule.name} $(date +%Y-%m-%d)"`,
    ].join('\n'),
  };
}

export function pushStep(): WorkflowStep {
  return {
    name: 'Push changes',
    if: 'success()',
    run: 'git push origin "$GITCRON_BRANCH"',
  };
}

export function pushToBaseStep(base: string): WorkflowStep {
  return {
    name: 'Push changes',
    if: 'success()',
    run: `git push origin ${base}`,
  };
}

export function createPrStep(schedule: Schedule): WorkflowStep {
  const title = (schedule.branch?.pr_title || `gitcron: ${schedule.name} — {{date}}`)
    .replace('{{name}}', schedule.name)
    .replace('{{date}}', '$(date +%Y-%m-%d)');
  const base = schedule.branch?.base || 'main';
  const labels = schedule.branch?.pr_labels || [];
  const labelFlags = labels.map(l => `--label ${l}`).join(' ');

  return {
    name: 'Create pull request',
    if: 'success()',
    env: { GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
    run: [
      'git push origin "$GITCRON_BRANCH"',
      `gh pr create \\`,
      `  --title "${title}" \\`,
      `  --body "Auto-generated by gitcron" \\`,
      `  --base ${base} ${labelFlags}`,
    ].join('\n'),
  };
}

export function notifyFailureStep(schedule: Schedule): WorkflowStep[] {
  if (!schedule.notify?.on_failure) return [];

  return schedule.notify.on_failure
    .filter(n => n.type === 'issue')
    .map(n => {
      const title = (n.title || `gitcron: ${schedule.name} failed`).replace('{{name}}', schedule.name);
      const labels = n.labels || [];
      const labelFlags = labels.map(l => `--label ${l}`).join(' ');

      return {
        name: 'Notify on failure',
        if: 'failure()',
        env: { GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
        run: `gh issue create --title "${title}" --body "Run failed. Check workflow logs." ${labelFlags}`,
      };
    });
}

export function reminderIssueStep(reminder: Reminder): WorkflowStep {
  const title = reminder.action.title || reminder.name;
  const body = reminder.action.body || '';
  const labels = reminder.action.labels || [];
  const assignees = reminder.action.assignees || [];
  const labelFlags = labels.map(l => `--label "${l}"`).join(' ');
  const assigneeFlags = assignees.map(a => `--assignee "${a}"`).join(' ');

  return {
    name: `Reminder: ${reminder.name}`,
    env: { GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
    run: `gh issue create --title "${title}" --body "${body}" ${labelFlags} ${assigneeFlags}`.trim(),
  };
}

export function oneShotGuardStep(at: string): WorkflowStep {
  return {
    name: 'Check if one-shot should fire',
    run: [
      `TARGET="${at}"`,
      'TARGET_TS=$(date -d "$TARGET" +%s 2>/dev/null || date -jf "%Y-%m-%dT%H:%M:%SZ" "$TARGET" +%s)',
      'NOW_TS=$(date +%s)',
      'DIFF=$((NOW_TS - TARGET_TS))',
      'if [ "$DIFF" -lt 0 ] || [ "$DIFF" -gt 3600 ]; then',
      '  echo "Not time yet or already past. Skipping."',
      '  exit 0',
      'fi',
    ].join('\n'),
  };
}

export type { WorkflowStep };
