import { createHash } from 'node:crypto';
import yaml from 'js-yaml';
import type { Schedule, Reminder, Settings, CronConfig } from '../utils/loader.js';
import {
  checkoutStep,
  setupNodeStep,
  installGitagentStep,
  installGitclawStep,
  createBranchStep,
  runAgentStep,
  runGitclawAgentStep,
  runCommandStep,
  commitStep,
  pushStep,
  pushToBaseStep,
  createPrStep,
  notifyFailureStep,
  reminderIssueStep,
  oneShotGuardStep,
  type WorkflowStep,
} from './steps.js';

interface GeneratedWorkflow {
  filename: string;
  content: string;
  hash: string;
  source: string;
}

function computeHash(input: string): string {
  return createHash('sha256').update(input).digest('hex').slice(0, 12);
}

function buildHeader(source: string, hash: string): string {
  return [
    '# AUTO-GENERATED by gitcron — do not edit manually',
    `# Source: cron.yaml → ${source}`,
    `# Hash: ${hash}`,
    '',
  ].join('\n');
}

function stepToObj(step: WorkflowStep): Record<string, unknown> {
  const obj: Record<string, unknown> = { name: step.name };
  if (step.uses) obj.uses = step.uses;
  if (step.with) obj.with = step.with;
  if (step.run) obj.run = step.run;
  if (step.if) obj.if = step.if;
  if (step.env) obj.env = step.env;
  return obj;
}

function buildScheduleWorkflow(schedule: Schedule, settings?: Settings): GeneratedWorkflow {
  const prefix = settings?.workflow_prefix || 'gitcron-';
  const filename = `${prefix}${schedule.name}.yml`;
  const source = `schedules.${schedule.name}`;
  const sourceHash = computeHash(JSON.stringify(schedule));

  const authorName = settings?.commit_author?.name || 'gitcron[bot]';
  const authorEmail = settings?.commit_author?.email || 'gitcron[bot]@users.noreply.github.com';

  const strategy = schedule.branch?.strategy || 'none';
  const base = schedule.branch?.base || 'main';

  const isGitclaw = schedule.adapter === 'gitclaw';

  // Build steps
  const steps: WorkflowStep[] = [checkoutStep()];

  if (schedule.agent) {
    steps.push(setupNodeStep());
    steps.push(isGitclaw ? installGitclawStep() : installGitagentStep());
  }

  if (strategy === 'pr' || strategy === 'create') {
    steps.push(createBranchStep(schedule));
  }

  if (schedule.agent) {
    steps.push(isGitclaw ? runGitclawAgentStep(schedule) : runAgentStep(schedule));
  } else if (schedule.command) {
    steps.push(runCommandStep(schedule));
  }

  if (strategy !== 'none') {
    steps.push(commitStep(schedule, authorName, authorEmail));
  }

  if (strategy === 'pr') {
    steps.push(createPrStep(schedule));
  } else if (strategy === 'create') {
    steps.push(pushStep());
  } else if (strategy === 'commit') {
    steps.push(pushToBaseStep(base));
  }

  steps.push(...notifyFailureStep(schedule));

  // Build env
  const envBlock: Record<string, string> = {};
  if (schedule.env) {
    Object.assign(envBlock, schedule.env);
  }

  // Build timeout
  const timeoutMinutes = schedule.timeout ? Math.ceil(schedule.timeout / 60) : 30;

  // Build permissions based on strategy
  const permissions: Record<string, string> = { contents: 'write' };
  if (strategy === 'pr') {
    permissions['pull-requests'] = 'write';
  }
  if (schedule.notify?.on_failure?.some(n => n.type === 'issue')) {
    permissions.issues = 'write';
  }

  const workflow: Record<string, unknown> = {
    name: `gitcron: ${schedule.name}`,
    on: {
      schedule: [{ cron: schedule.cron }],
      workflow_dispatch: {
        inputs: {
          prompt: {
            description: 'Override prompt',
            required: false,
            type: 'string',
          },
        },
      },
    },
    concurrency: {
      group: `gitcron-${schedule.name}`,
      'cancel-in-progress': false,
    },
    jobs: {
      run: {
        'runs-on': 'ubuntu-latest',
        'timeout-minutes': timeoutMinutes,
        permissions,
        ...(Object.keys(envBlock).length > 0 ? { env: envBlock } : {}),
        steps: steps.map(stepToObj),
      },
    },
  };

  const yamlContent = yaml.dump(workflow, {
    lineWidth: -1,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false,
  });

  const content = buildHeader(source, sourceHash) + yamlContent;

  return { filename, content, hash: sourceHash, source };
}

function buildReminderWorkflow(reminder: Reminder, settings?: Settings): GeneratedWorkflow {
  const prefix = settings?.workflow_prefix || 'gitcron-';
  const filename = `${prefix}reminder-${reminder.name}.yml`;
  const source = `reminders.${reminder.name}`;
  const sourceHash = computeHash(JSON.stringify(reminder));

  const steps: WorkflowStep[] = [checkoutStep()];

  if (reminder.type === 'one-shot' && reminder.at) {
    steps.push(oneShotGuardStep(reminder.at));
  }

  if (reminder.action.type === 'issue') {
    steps.push(reminderIssueStep(reminder));
  }

  // For one-shot, fire near the target time — use a daily check cron
  const cron = reminder.type === 'recurring' ? reminder.cron! : '0 */1 * * *';

  const workflow: Record<string, unknown> = {
    name: `gitcron: reminder-${reminder.name}`,
    on: {
      schedule: [{ cron }],
      workflow_dispatch: {},
    },
    concurrency: {
      group: `gitcron-reminder-${reminder.name}`,
      'cancel-in-progress': false,
    },
    jobs: {
      remind: {
        'runs-on': 'ubuntu-latest',
        'timeout-minutes': 5,
        permissions: {
          issues: 'write',
        },
        steps: steps.map(stepToObj),
      },
    },
  };

  const yamlContent = yaml.dump(workflow, {
    lineWidth: -1,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false,
  });

  const content = buildHeader(source, sourceHash) + yamlContent;

  return { filename, content, hash: sourceHash, source };
}

export function generateWorkflows(config: CronConfig): GeneratedWorkflow[] {
  const workflows: GeneratedWorkflow[] = [];

  if (config.schedules) {
    for (const schedule of config.schedules) {
      if (schedule.enabled === false) continue;
      workflows.push(buildScheduleWorkflow(schedule, config.settings));
    }
  }

  if (config.reminders) {
    for (const reminder of config.reminders) {
      if (reminder.enabled === false) continue;
      workflows.push(buildReminderWorkflow(reminder, config.settings));
    }
  }

  return workflows;
}

export type { GeneratedWorkflow };
